name: Release Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build plugin
        run: npm run build
      
      - name: Prepare release package
        run: |
          mkdir -p release-package/dist
          cp dist/index.js release-package/dist/
          cp icon.svg release-package/
          cp README.md release-package/
          cd release-package
          zip -r ../orca-week-calendar-${{ github.ref_name }}.zip .
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: orca-week-calendar-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

